pypro/aperitivos/urls.py
from django.urls import path, include

from pypro.aperitivos.views import video, indice
app_name='aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),

]

pypro/base/urls.py
from django.urls import path, include

from pypro.base.views import home

app_name='base'
urlpatterns = [
    path('', home, name='home'),

]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from pypro.base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )
    

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django .utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError('The given username must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class

    email and password are required. Other fields are optional.
    """
 

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
       
    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/aperitivos/views.py
from django.db.models.fields import SlugField
from django.shortcuts import render, get_object_or_404
from pypro.aperitivos.model import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %} 
{% load static %}
{%block title%}Python Pro - aperitivo{% endblock title%}
{% block description %}Página com todos os vídeos gratuitos{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">Lista de vídeos aperitivos</h1>
                <ol>
                    {% for video in videos %}
                        <li><a href="{{ video.get_absolute_url }}">{{ video.titulo |default:"Faltando Titulo" }}</a></li>
                    {% empty %}
                        <li>Nao foi encontrado nenhum video de aperitivo</li>
                    {% endfor %}
                </ol>

            </div> 
        </div>
    </div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %} 
{% load static %}
{%block title%}Python Pro - Video{% endblock title%}
{% block description %}Página de vídeo gratuito de Python{% endblock description %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 class="mt-4 mb-3">{{ video.titulo |default:"Faltando Titulo" }}</h1>
                <iframe width="640" height="320" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
        </div>
    </div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	
	<title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Pagina do curso Python Pro{% endblock description %}">
	<meta name="author" content="Eduardo Vale">
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-bs-target="#navbarSupportedContent"
			aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      		<span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
    </div>
</nav>
{% block body %}{% endblock body %}

{% include 'base/footer.html' with contato_email='teste@teste.com' only %}
</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-3 pt-3 text-light">
	<div class="container">
		<div class="row">
			<div class="col">
				<h3>Entre em contato</h3>
				<address>
					+55 84 555-55555
					<br>
					<a href="mailto:{{contato_email}}" class="text-light">{{contato_email}}</a>
				</address>
			</div>
		</div>
	</div>
	<div class="rights pb-2">
		<div class="container">
			<div class="row">
				<div class="col">
					{% now 'Y' %} Python Pro. Todos os direitos reservados.
				</div>
			</div>
		</div>
	</div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %} 
{% load static %}
{%block title%}Python Pro - Home{% endblock title%}
{% block body %}
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="jumbotron">
				<h2 class="mr-lg-4">
					<br>
					Curso de Python com Luciano Rvamalho
				</h2>
				<h4 class="mt-4">Matriculas abertas</h4>
				<!-- INICIO DO BOTAO PAGSEGURO -->
				<a href="https://pag.ae/7WUWzRNsM/button" target="_blank" title="Pagar com PagSeguro">
				<img src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif" alt="Pague com PagSeguro - é rápido, grátis e seguro!"/>
				</a>
				<br>
				<!-- FIM DO BOTAO PAGSEGURO -->
{#					<h4 class="mt-4">Entre na Lista de espera</h4>#}
{#				<form action="https://gmail.us2.list-manage.com/subscribe/post?u=7db2392aabd7652112727a48c&amp;id=9870346765" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>#}
{#				   <div class="form-row align-items-center">#}
{#                    <div class="col-auto">#}
{#                            <label class="sr-only" for="mce-EMAIL">Email</label>#}
{#                           <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL"#}
{#                                   placeholder="exemplo@email.com">#}
{#                        </div>#}
{#                        <div class="col-auto">#}
{#                           <label class="sr-only" for="mce-FNAME">Nome</label>#}
{#   							<input type="text" class="form-control mb-2 mr-sm-2" id="mce-FNAME" placeholder="Seu Nome">#}
{#						</div>#}
{#    				<!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->#}
{#  				   <div style="position: absolucould i have a statement, please?te; left: -5000px;" aria-hidden="true"><input type="text" name="b_a4954439a852f86a833c5a5ab_d9c6db188d" tabindex="-1"value=""></div>#}
{#				   <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary"></div>#}
{#   			 	</form>#}
				<!-- <p>
					Confira em breve mais informações sobre o curso que será ministrado pelo autor do livro
					<a href="https://novatec.com.br/livros/pythonfluente/" target="_blank" >Python Fluente</a>
				</p> -->
			</div>
		</div>
		
	</div>
	<div class="row">

		<div class="col-md-12">
			<div class="card">
				<h5 class="card-header">
					Mais detalhes sobre o instrutor
				</h5>
				<div class="card-body">
					<p class="card-text">
						<img src="{% static 'img/luciano-ramalho2.jpeg' %}" alt="Foto de Luciano Ramalho" class="img-thumbnail float-lg-start"/>
						Luciano Ramalho is a Technical Principal at ThoughtWorks and the author of Fluent Python (OReilly, 2015).Ramalho was a web developer before the Netscape IPO in 1995,and has worked on some of the largest news portals in Brazil using Python since 1998.He has spoken multiple times at OSCON, PyCon, PythonBrasil, FISL, and RuPy. Ramalho is a fellow of the Python Software Foundation and co-founder of Garoa Hacker Clube, the first hackerspace in Brazil.
					</p>
				</div>
			</div>
		</div>
	</div>	
</div>
{% endblock body %}